[package]
name = "yoshino"
edition = "2024"
# license = "MIT"
# authors = ["Yoshino Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "testnet" }
token = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/token", rev = "testnet" }

[addresses]
yoshino = "0x0"
# Note: The following addresses will be resolved from the published packages on testnet
# sui = "0x2"
# deepbook and token addresses are resolved via git dependencies

# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
